# ProjectEuler.net
# Even Fibonacci numbers
# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibo=1
prefibo=0
summa=0
stopper=4000000

while fibo<stopper
    a=fibo
    fibo=fibo+prefibo
    prefibo=a
    puts fibo
    if fibo%2==0 && fibo<stopper
        summa=summa+fibo
    end
end

puts "Answer is: #{summa}"

# answer: 4613732
