
////////////////////////////////////////////////////////////////////
/*
ProjectEuler.net
Multiples of 3 and 5
Problem 1

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.
*/
problem001 = function(){
userInput = document.getElementById("input1").value;
var summa=0;
var a=userInput;
for (var i = 1; i < a; i++) {
    if(i%3==0){
        /*console.log(i);*/
        summa=summa+i;
    }
    else{
        if(i%5==0){
            /*console.log(i);*/
            summa=summa+i;
        }
    }
}
console.log("Answer is:");
console.log(summa);
document.getElementById("output1").innerHTML = summa;
};
/*answer: 233168*/

////////////////////////////////////////////////////////////////////

/*
ProjectEuler.net
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

problem002=function(){
userInput = document.getElementById("input2").value;
var fibo=1;
var prefibo=0
var summa=0;
var stopper=userInput;

while(fibo<stopper) {
    var a=fibo;
    fibo=fibo+prefibo;
    prefibo=a;
    console.log(fibo);
    if(fibo%2==0 && fibo<stopper){
        /*console.log(i);*/
        summa=summa+fibo;
    }
}

console.log("Answer is:");
console.log(summa);
document.getElementById("output2").innerHTML = summa;
};
/*answer: 4613732*/


////////////////////////////////////////////////////////////////////


/*
Largest prime factor
Problem 3

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

*/

//function to test if testNumber is prime number
var isPrime = function (testNumber) {
    for (var j = 2; j<testNumber; j++){
      if(testNumber%j==0){return 0;}
    }
      return testNumber;
};


problem003=function(){
userInput = document.getElementById("input3").value;
var number=userInput;
//var number=600851475143;
//var number=600851475;
var divNumber=number;
var maxsize=Math.floor(Math.sqrt(number));
//console.log("Start from: ", maxsize);
var answer=0;
var divisor=[];
var index=0;


// Find divisors that are below number's square root
for (var i = maxsize; i > 1; i--) {
    while(divNumber%i==0){    
        //console.log("Number", i, "is divisible with", divNumber); 
        answer=isPrime(i);
        if(answer!==0){
          //console.log(answer, "is prime");
          divisor[index]=answer; 
          index++;
          divNumber=divNumber/answer;
        }
        else{
          //console.log(i, "is not prime number"); 
          break;
        }
    }
}
    console.log("Divisors");
    console.log(divisor);


// Check largest divisor as it can be larger than SQRT(number)
for(var k=0; k<divisor.length; k++){
    number=number/divisor[k];
    console.log(number);
}
if (number===1){answer=divisor[0];}
else {answer=number}
console.log("Answer is:");
console.log(answer);
document.getElementById("output3").innerHTML = answer;
};
/*Answer is 6857*/