/*
ProjectEuler.net
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var fibo=1;
var prefibo=0
var summa=0;
var stopper=4000000;

while(fibo<stopper) {
    var a=fibo;
    fibo=fibo+prefibo;
    prefibo=a;
    console.log(fibo);
    if(fibo%2==0 && fibo<stopper){
        /*console.log(i);*/
        summa=summa+fibo;
    }
}

console.log("Answer is:");
console.log(summa);

/*answer: 4613732*/